#!/bin/sh
#
# commit-msg.sh
#
# Removes Comment Markers around the meta information generated by
# the prepare-commit-msg git hook
#
# To enable this hook, rename this file to "commit-msg".

echo "$(cat "$1" | perl -p -e 's/#!()/$1/')" > "$1"
